-- Tablas Maestras: Solo el nombre es obligatorio
CREATE TABLE CIUDAD_REGION (
    "CIUDAD_REGION_ID" SERIAL PRIMARY KEY,
    "CIUDAD_REGION" VARCHAR(255) NOT NULL -- Si no hay nombre, no hay registro
);

CREATE TABLE CURSOS (
    "CURSO_ID" SERIAL PRIMARY KEY,
    "CURSO" VARCHAR(255) NOT NULL UNIQUE,
    "VALOR_UNITARIO" NUMERIC(12, 2) -- Quitamos NOT NULL por si el precio varía
);

CREATE TABLE DESCUENTO (
    "DESCUENTO_ID" SERIAL PRIMARY KEY,
    "DESCUENTO" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE GENERO (
    "GENERO_ID" SERIAL PRIMARY KEY,
    "GENERO" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MEDIO_DE_PAGO (
    "MEDIO_DE_PAGO_ID" SERIAL PRIMARY KEY,
    "MEDIO_DE_PAGO" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MODALIDAD (
    "MODALIDAD_ID" SERIAL PRIMARY KEY,
    "MODALIDAD" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROCEDENCIA (
    "PROCEDENCIA_ID" SERIAL PRIMARY KEY,
    "PROCEDENCIA" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROFESION (
    "PROFESION_ID" SERIAL PRIMARY KEY,
    "PROFESION" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE RESPONSABLE_VENTA (
    "RESPONSABLE_VENTA_ID" SERIAL PRIMARY KEY,
    "RESPONSABLE_VENTA" VARCHAR(100) NOT NULL UNIQUE
);

-- Tabla de Clientes: Muy flexible
CREATE TABLE CLIENTES (
    "CLIENTE_ID" SERIAL PRIMARY KEY,
    "NUMERO_DE_IDENTIFICACION" VARCHAR(50) NOT NULL UNIQUE, -- Obligatorio para no duplicar
    "PRIMER_APELLIDO" VARCHAR(100), -- Quitamos NOT NULL
    "SEGUNDO_APELLIDO" VARCHAR(100),
    "PRIMER_NOMBRE" VARCHAR(100), -- Quitamos NOT NULL
    "SEGUNDO_NOMBRE" VARCHAR(100),
    "FECHA_DE_NACIMIENTO" DATE,
    "GENERO_ID" INTEGER REFERENCES GENERO ("GENERO_ID"),
    "CELULAR" VARCHAR(20),
    "CORREO" VARCHAR(150),
    "CIUDAD_REGION_ID" INTEGER REFERENCES CIUDAD_REGION ("CIUDAD_REGION_ID"),
    "PROFESION_ID" INTEGER REFERENCES PROFESION ("PROFESION_ID")
);

-- Tabla de Hechos (Fact Table): Flexible para actualizaciones posteriores
CREATE TABLE fact_ventas (
    "VENTA_ID" SERIAL PRIMARY KEY,
    "CLIENTE_ID" INTEGER REFERENCES CLIENTES ("CLIENTE_ID"), -- Quitamos NOT NULL
    "CURSO_ID" INTEGER REFERENCES CURSOS ("CURSO_ID"),     -- Quitamos NOT NULL
    "MODALIDAD_ID" INTEGER REFERENCES MODALIDAD ("MODALIDAD_ID"),
    "RENOVACION" VARCHAR(10) DEFAULT 'No',
    "RESPONSABLE_VENTA_ID" INTEGER REFERENCES RESPONSABLE_VENTA ("RESPONSABLE_VENTA_ID"),
    "FECHA_DE_VENTA" DATE, -- Quitamos NOT NULL
    "DESCUENTO_ID" INTEGER REFERENCES DESCUENTO ("DESCUENTO_ID"),
    "PRECIO_NETO" NUMERIC(12, 2) DEFAULT 0, -- Ponemos default 0 en lugar de obligar
    "MEDIO_DE_PAGO_ID" INTEGER REFERENCES MEDIO_DE_PAGO ("MEDIO_DE_PAGO_ID"),
    "FECHA_DE_PAGO" DATE,
    "ELABORO" INTEGER REFERENCES RESPONSABLE_VENTA ("RESPONSABLE_VENTA_ID"),
    "PROCEDENCIA_ID" INTEGER REFERENCES PROCEDENCIA ("PROCEDENCIA_ID"),
    "SEGUIMIENTO_POST_VENTA" VARCHAR(255)
);