
CREATE TABLE CIUDAD_REGION (
    "CIUDAD_REGION_ID" INTEGER PRIMARY KEY,
    "CIUDAD_REGION" VARCHAR(255) NOT NULL
);

CREATE TABLE CURSOS (
    "CURSO_ID" INTEGER PRIMARY KEY,
    "CURSO" VARCHAR(255) NOT NULL UNIQUE,
    "VALOR_UNITARIO" NUMERIC(10, 2) NOT NULL
);

CREATE TABLE DESCUENTO (
    "DESCUENTO_ID" INTEGER PRIMARY KEY,
    "DESCUENTO" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE GENERO (
    "GENERO_ID" INTEGER PRIMARY KEY,
    "GENERO" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MEDIO_DE_PAGO (
    "MEDIO_DE_PAGO_ID" INTEGER PRIMARY KEY,
    "MEDIO_DE_PAGO" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MODALIDAD (
    "MODALIDAD_ID" INTEGER PRIMARY KEY,
    "MODALIDAD" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROCEDENCIA (
    "PROCEDENCIA_ID" INTEGER PRIMARY KEY,
    "PROCEDENCIA" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROFESION (
    "PROFESION_ID" INTEGER PRIMARY KEY,
    "PROFESION" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE RESPONSABLE_VENTA (
    "RESPONSABLE_VENTA_ID" INTEGER PRIMARY KEY,
    "RESPONSABLE_VENTA" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CLIENTES (
    "CLIENTE_ID" SERIAL PRIMARY KEY,
    "NUMERO_DE_IDENTIFICACION" VARCHAR(50) NOT NULL UNIQUE,
    "PRIMER_APELLIDO" VARCHAR(100) NOT NULL,
    "SEGUNDO_APELLIDO" VARCHAR(100),
    "PRIMER_NOMBRE" VARCHAR(100) NOT NULL,
    "SEGUNDO_NOMBRE" VARCHAR(100),
    "FECHA_DE_NACIMIENTO" DATE,
    "GENERO_ID" INTEGER REFERENCES GENERO ("GENERO_ID"),
    "CELULAR" VARCHAR(20),
    "CORREO" VARCHAR(150),
    "CIUDAD_REGION_ID" INTEGER REFERENCES CIUDAD_REGION ("CIUDAD_REGION_ID"),
    "PROFESION_ID" INTEGER REFERENCES PROFESION ("PROFESION_ID")
);

CREATE TABLE fact_ventas (
    "VENTA_ID" SERIAL PRIMARY KEY,
    "CLIENTE_ID" INTEGER NOT NULL REFERENCES CLIENTES ("CLIENTE_ID"),
    "CURSO_ID" INTEGER NOT NULL REFERENCES CURSOS ("CURSO_ID"),
    "MODALIDAD_ID" INTEGER NOT NULL REFERENCES MODALIDAD ("MODALIDAD_ID"),
    "RENOVACION" BOOLEAN DEFAULT FALSE,
    "RESPONSABLE_VENTA_ID" INTEGER NOT NULL REFERENCES RESPONSABLE_VENTA ("RESPONSABLE_VENTA_ID"),
    "FECHA_DE_VENTA" DATE NOT NULL,
    "DESCUENTO_ID" INTEGER REFERENCES DESCUENTO ("DESCUENTO_ID"),
    "PRECIO_NETO" NUMERIC(12, 2) NOT NULL,
    "MEDIO_DE_PAGO_ID" INTEGER NOT NULL REFERENCES MEDIO_DE_PAGO ("MEDIO_DE_PAGO_ID"),
    "FECHA_DE_PAGO" DATE,
    "ELABORO" INTEGER NOT NULL REFERENCES RESPONSABLE_VENTA ("RESPONSABLE_VENTA_ID"),
    "PROCEDENCIA_ID" INTEGER REFERENCES PROCEDENCIA ("PROCEDENCIA_ID"),
    "SEGUIMIENTO_POST-VENTA" VARCHAR(255),

    -- Se incluye CHECK para asegurar que el precio sea positivo
    CHECK ("PRECIO_NETO" >= 0)
);